[[redirects]]
  from = "/cors-proxy/*"
  to = "https://geo.ipify.org/api/v1:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values] 
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"
    